version: '3.9'
services:
  db:
    build: ./
    container_name: ${PRJ_NAME}db
    environment:
      MYSQL_ROOT_PASSWORD: xpto
      MYSQL_DATABASE: xpto
      MYSQL_USER: xpto
      MYSQL_PASSWORD: xpto
    volumes:
      - ./dados:/dados
      - ./src:/src
    ports:
      - 3306:3306
    networks:
      - db
      
  backup_agent:
    build: ./backup_agent
    container_name: ${PRJ_NAME}backup_agent
    tty: true
    volumes:
      - ./dados:/dados
    networks:
      - db
    depends_on:
      - db
    

networks:
  db:
volumes:
  data: 